name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.LIGHTSAIL_IP }}
        username: ubuntu
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          # Install Node.js and npm if not installed
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

          # Install PM2 if not installed
          if ! command -v pm2 &> /dev/null; then
            sudo npm install -g pm2
          fi

          # Create project directory if it doesn't exist
          mkdir -p /home/ubuntu/capstone-node

          # Clone repository if it doesn't exist
          if [ ! -d "/home/ubuntu/capstone-node/.git" ]; then
            cd /home/ubuntu
            git clone https://github.com/2025CAPSTONE-WOONG/capstone-node.git
          fi

          # Deploy application
          cd /home/ubuntu/capstone-node
          git pull origin main
          npm install
          pm2 describe capstone-node > /dev/null || pm2 start src/index.js --name capstone-node
          pm2 restart capstone-node
          pm2 save 